feat: UI add breadcrumbs step1
dcrtit/kit pull request #10
Opened 2022-02-04 08:19 UTC by fotomexanik

#3 #4

2022-02-04 10:40 UTC, lennoximus requested changes

2022-02-04 13:12 UTC, lennoximus commented
Принимаем? Или еще storybook будет тут?

2022-02-07 08:19 UTC, lennoximus requested changes
Давай еще линтером пройдемся по файлам, чтобы все в одном кодовом стиле было.

2022-02-07 08:19 UTC, lennoximus commented on packages/ui/src/Breadcrumbs/Breadcrumbs.stories.js
> +      '     <CBreadcrumbs>',
Давай через строковые шаблоны запишем, так удобнее с точки зрения читаемости будет. Меняем везде, где описываем в сторис template.

2022-02-07 15:47 UTC, fotomexanik commented on packages/ui/src/Breadcrumbs/Breadcrumbs.stories.js
> +      '     <CBreadcrumbs>',
Поправил template

2022-02-08 08:48 UTC, merged